# Available Version Overrides (.env)
#
# _MINIO_VERSION  - Use to pin the minio version (eg. RELEASE.2021-06-07T21-40-51Z)
#                   Default: minio/minio:latest
# _REDIS_VERSION  - Use to pin the version of Redis (eg. 6.2)
#                   Default: redis:latest

version: '3'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - ${DATA_ENGINEERING_BASEDIR}/minio/data:/data
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_admin
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
    networks:
      - mde
    hostname: minio
    restart: always
  
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${DATA_ENGINEERING_BASEDIR}/mysql/data/mysqldir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=dataeng
      - MYSQL_PASSWORD=dataengineering_user
      - MYSQL_ROOT_PASSWORD=dataengineering
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - mde
    hostname: mysql
    restart: always
  
  redis:
    image: redis:${_REDIS_VERSION:-latest}
    container_name: redis
    hostname: redis
    networks:
      - mde
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

networks:
    mde:
        external: true
        name: mde
